Create User-Search-Function
TakashiMorise/new_chat-space pull request #7
Opened 2019-01-13 03:24 UTC by TakashiMorise

# WHAT
Create user-search-function.

# WHY
To improve a operability of the Application.
***
- add user-search area in the view.
- make a js-file.
- edit controller
- change communication with json.
- change groups-form(used edit & new)view.
- add processing when asynchronous communication fails.

2019-01-14 04:41 UTC, TakashiMorise commented
I finished this task!
Please check my code!

2019-01-14 04:54 UTC, kuroko918 commented
インクリメンタルサーチの挙動を見せてください！

2019-01-14 04:54 UTC, kuroko918 commented on app/assets/javascripts/application.js
> +//= require jquery.turbolinks
このgemは廃止予定のgemみたいでturbolinksのv5系では動かないみたいなので、消しておいてください！

2019-01-14 04:54 UTC, kuroko918 commented on app/assets/javascripts/user-search.js
> +$(function(){
こちらを`$('document').on('turbolinks:load', function(){`とするとtubolinksによるjQueryの阻害が解除されます！

2019-01-14 04:54 UTC, kuroko918 commented on app/assets/javascripts/user-search.js
> +    console.log(name);
console.logは消しましょう！

2019-01-14 04:54 UTC, kuroko918 commented on app/assets/javascripts/user-search.js
> +  function removeUser(userId, name) {
removeUserという名前はuserを削除するかのような名前なので、addUserでいいかと思います！

2019-01-14 04:54 UTC, kuroko918 commented on app/views/groups/_form.html.haml
>      / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
不要なコメントは消しておきましょう！

2019-01-14 04:54 UTC, kuroko918 commented on app/views/groups/_form.html.haml
> +        %input#user-search-field.chat-group-form__input{:placeholder => "追加したいユーザー名を入力してください", :type => "text"}/
こちらはヘルパーメソッドを使って書き換えられますか？

2019-01-14 04:54 UTC, kuroko918 commented on app/views/groups/haml_change.html.erb
> +<!-- この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します サーチ部分-->
このファイルは要りますか？

2019-01-14 04:54 UTC, kuroko918 commented on app/views/groups/haml_change.html.erb
> +<!-- この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します 結果表示-->
不要なコメントは消しておきましょう！

2019-01-14 04:54 UTC, kuroko918 commented on app/views/groups/haml_change.html.haml
> +/ この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します サーチ部分
不要なコメントは消しておきましょう！

2019-01-14 04:54 UTC, kuroko918 commented on app/views/groups/haml_change.html.haml
> +/ この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します 結果表示
不要なコメントは消しておきましょう！

2019-01-14 04:54 UTC, kuroko918 commented on app/views/groups/tmp.file
> +<!-- この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します サーチ部分-->
このファイルは要りますか?

2019-01-14 06:03 UTC, TakashiMorise commented on app/assets/javascripts/application.js
> +//= require jquery.turbolinks
gem uninstallでアンインストールしました。
また、Gemfile, Gemfile.lockを編集しました。

2019-01-14 06:07 UTC, TakashiMorise commented on app/assets/javascripts/user-search.js
> +$(function(){
turbolinksによるjQueriyの阻害と言うのは、リロードしないとjQueryのプログラムが機能しない、と言う問題でしょうか？
これの解決法を探しておりました！！ありがとうございます。修正いたします

2019-01-14 06:08 UTC, TakashiMorise commented on app/assets/javascripts/user-search.js
> +    console.log(name);
申し訳ございません、見直したつもりになっていました。。。
削除いたしました。

2019-01-14 06:13 UTC, TakashiMorise commented on app/views/groups/_form.html.haml
>      / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
こういった細かな作業がきちんとできてませんでした。
少し急ぎ過ぎた感があります。今後は最終チェックを厳にいたします。

2019-01-14 06:15 UTC, TakashiMorise commented on app/views/groups/haml_change.html.erb
> +<!-- この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します サーチ部分-->
hamlを作るのに残しておいたファイルです。
最終的には削除いたしますが、この後の復習用にいまは残させてください。
復習後にどこかにコピペで移動いたします。

2019-01-14 06:17 UTC, TakashiMorise commented on app/views/groups/haml_change.html.haml
> +/ この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します サーチ部分
上記ファイルと違ってこちらのファイルは特に不要となりますので、ファイルごと削除いたしました。

2019-01-14 06:23 UTC, TakashiMorise commented on app/views/groups/haml_change.html.haml
> +/ この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します 結果表示
こちらのファイルも削除いたします。無駄な修正を確認してもらうことになり申し訳ございませんでした。

2019-01-14 06:24 UTC, TakashiMorise commented on app/views/groups/tmp.file
> +<!-- この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します サーチ部分-->
最終的には削除いたしますが、本課題を今一度復習したく、
今のところは残させてください。
デプロイまでにどこかにコピべして削除いたします。

2019-01-14 07:45 UTC, TakashiMorise commented
インクリメンタルサーチの動画をお送りします。

2019-01-14 07:57 UTC, TakashiMorise commented on app/assets/javascripts/user-search.js
> +$(function(){
記載してみたのですが、プログラム自体が機能しなくなってしまって。。。
とりあえず元に戻しました。原因究明します。

2019-01-14 08:01 UTC, TakashiMorise commented
動画を撮っている時に分かったのですが、
最終的に「登録する」ボタンを押してできた新しいグループ、編集したグループからは、自分自身が外されてしまいメイン画面に表示されないと言うことがわかりました。
登録前までの挙動ばかり気にして気付いていませんでした。
現在原因究明中ですが、難航しています。何かヒントがあれば教えてください。

2019-01-14 08:16 UTC, takebn26 requested changes

2019-01-14 08:16 UTC, takebn26 commented on app/views/groups/tmp.file
> +<!-- この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します サーチ部分-->
その場合レビュー対象には入らないので、.gitignoreに含めてしまいましょう

2019-01-14 08:18 UTC, takebn26 commented
turbolinks:loadのところは記述は他メンターが前述した通りなので、動かないのがなぜか原因究明する必要がありますね

自分自身をコントローラーのアクションの中で含むような記述が必要になってきます
そちらが記載されているか確認するのがいいと思います

2019-01-17 11:53 UTC, TakashiMorise commented on app/assets/javascripts/user-search.js
> +$(function(){
$(document).on....とすることでプログラムが動作するようになりました。解決です。

2019-01-17 11:55 UTC, TakashiMorise commented on app/views/groups/tmp.file
> +<!-- この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します サーチ部分-->
復習も終わり、ファイルは別に移動してアプリ上からは削除いたしました。

2019-01-17 12:02 UTC, TakashiMorise commented
https://i.gyazo.com/696657951f2a62c7f7210f712bf21f4e.mp4?_ga=2.199954157.2121688617.1547726337-1651028204.1541500839

動画短いですけど送ります。

2019-01-17 12:06 UTC, TakashiMorise commented
JSの動作、Viewの画面、新規作成・編集の両ページで上手く動作するようになりました。
ご確認よろしくお願いいたします。

2019-01-17 12:12 UTC, yutakatahira commented on app/assets/javascripts/user-search.js
> +    var name = $(this).attr('data-user-name');
attrではなく、data()を使いましょう！

2019-01-18 08:35 UTC, TakashiMorise commented on app/assets/javascripts/user-search.js
> +    var name = $(this).attr('data-user-name');
data()に変更しました。
なんで（'data-user-id'）と記載されたいるのかがわかりました。
確認よろしくお願いいたします。

2019-01-18 08:39 UTC, kuroko918 commented
いいかと思います！
LGTMです！

2019-01-18 10:04 UTC, merged